### ISSUE TITLE
Measure Issue Creation Rate and Issue Closure Rate per week/month per repo

### ISSUE THREAD

**Issue by EvanKepner** [EvanKepner/bazaar#30]

**Comment by andrea-soto** [comment]
I've aggregated the IssuesEvents to get the total open and closed event by week by repo.

I tried to get some stats in mongo (min,max,avg,std) but realized the results were biased because it only includes the counts for the week were an event exists. So for example, as repo with only 1 issue opened in a year had an average issues per week of 1. However, the average should be 1/52.

I found it difficult to do a real average on mongo (because I would have to add 0s to all the weeks that have not events), so I'm going to take the weekly data and do some analysis in python instead.
